### ISSUE TITLE
打印二维码问题

### ISSUE THREAD

**Issue by cinos1** [SubLuLu/thermal_printer#4]
我在java中直接打印二维码，系统直接输出原始地址同时在前面加了1P0，后面加1E01C1Q0,请问是怎么回事呢，文本和条形码都可以正常输出

**Comment by SubLuLu** [comment]
你的打印机不支持二维码 可以通过代码生成二维码 以图片的方式进行打印

**Comment by cinos1** [comment]
好的，感谢，这两天通过生成二维码调用您写好的图片类，已经可以正常输出二维码了。
