### ISSUE TITLE
外网部署的WEB应用，怎么调用不同地域通过浏览器WEB来打印小票。

### ISSUE THREAD

**Issue by lffsonic** [SubLuLu/thermal_printer#5]
看了示例，需要设置一个IP地址，web程序需要和打印机部署在同一局域网内才能访问，如果web程序在外网，不同餐厅通过浏览器访问web打印小票，餐厅内打印机是内网IP，部署在外网的web应用是无法访问打印机内网IP，发送打印指令的

**Comment by SubLuLu** [comment]
可以开发一个客户端 windows mac Linux android iOS 不管什么版本 放在内网里面 通过账号登录到外网的web应用 客户端和web应用通过socket保持长链接 所有的内网配置存储在客户端 客户端连接打印机 外网通过socket发送打印命令 客户端转发给打印机打印
