### ISSUE TITLE
图片打印是无效的?

### ISSUE THREAD

**Issue by Sivan757** [SubLuLu/thermal_printer#9]
仔细过了下图片打印那部分的代码,发现并不能打印,路径也是没有使用的..?

**Comment by SubLuLu** [comment]
`发现并不能打印` 请提交你的测试代码和测试结果，包括需要打印的图片和打印出来的结果
`路径也是没有使用的..? ` 请认真查看源码，最好是亲自实践测试

**Comment by Lazy-F** [comment]
抱歉..Bitmap

**Comment by Sivan757** [comment]
该问题是由于java web项目,无法调用安卓的Bitmap类出现的问题.
